### ISSUE TITLE
Not working unless running locally in VS

### ISSUE THREAD

**Issue by huwred** [KevinJump/Our.Umbraco.MaintenanceMode#16]
In Umbraco 8.10.1 you only get the maintenance page when running in VS, when turning on maintenance mode on the webserver you just get
'The service is unavailable.' 

So not very useful

**Comment by huwred** [comment]
In the RenderMVCController the code does the following
                    if (Response != null)
                        Response.StatusCode = (int)HttpStatusCode.ServiceUnavailable;

Which is what I assume is the reason for the error, any idea why? And what is the purpose of that check?

**Comment by huwred** [comment]
Ok, I believe this is happenining when CustomErrors are ON, any idea how to get around this?

**Comment by huwred** [comment]
just need to add the following custom error in web.config, so I don't think it is a code issue, happy for you to close this

<error statusCode="503"  redirect="/MaintenancePage" />

**Comment by PSinke** [comment]
> just need to add the following custom error in web.config, so I don't think it is a code issue, happy for you to close this

I'm now running into the same issue. 'The following custom error' seems to be missing from your post. Could you tell me what custom error it is?

**Comment by KevinJump** [comment]
hi it looks like (from the source of the comment) the fix was 

```
<error statusCode="503"  redirect="/MaintenancePage" />
```

@huwred  might be able to confirm.

**Comment by PSinke** [comment]
Thanks @KevinJump 
Unfortunately that still results the 'service is unavailable' notice for me. Even when turning off the custom errors. I'll keep trying other things. If I find out what caused it, I will update here.

**Comment by huwred** [comment]
Sorry for the delay, just realised thee were getting dumped in a spam folder.
That is what I added to get it working, but it has stopped now for a completely different reason will take a look.

**Comment by huwred** [comment]
UnderMaintenance is my custom template based on the original
