### ISSUE TITLE
Nuget for V2 - > Umbraco 8 

### ISSUE THREAD

**Issue by qz2rg4** [KevinJump/Our.Umbraco.MaintenanceMode#34]
Hi Kevin 

Are you planning to post V2 for Umbraco 8 to nuget ?  

Thanks

**Comment by KevinJump** [comment]
Hi, 

that's something i hadn't released we didn't do. & I don't think there was a technical reason why not. 

personally, I might not have the time to do this soon. but this package is open for contributions and marked for hacktoberfest 😄 so if you or anyone wanted to have a go, it would be counted as a contribution towards [Umbraco hacktoberfest stuff](https://umbraco.com/blog/umbraco-hacktoberfest-2022/).

i would be more than happy have a look over and PRs and push the package when its ready.
