### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by vinordic** [KevinJump/Our.Umbraco.MaintenanceMode#35]
Hi,

Is there a way to control the background image used?
I couldnt change to my own template, should that be working?

**Comment by KevinJump** [comment]
yeah you should be able to change to your own template, what version are you on?

**Comment by vinordic** [comment]
Umbraco 11

**Comment by Momkay** [comment]
@vinordic Can you verify this?

Doesn't seem to work on my end, I'm on 11.0.0.

`@inherits UmbracoViewPage<MaintenanceMode>
@using Our.Umbraco.MaintenanceMode.Models

@{
    Layout = "BaseLayout.cshtml";
}

<div class="maintenance">
    <div class="maintenance__inner">
        <h1>@Model.Title</h1>
        <p>@Model.Text</p>
    </div>
</div>`
